workflows:
  smart-accountant-workflow:
    name: Smart Accountant
    environment:
      flutter: 3.22.0
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build universal APK
        script: flutter build apk --debug --target-platform android-arm,android-arm64,android-x64
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
